---
title: "east iron carbon"
author: "dengyuanpei"
date: "2024-08-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list=ls())#clear Global Environment
#设置工作目录
setwd("C:\\Users\\yyds\\Desktop\\new")

#----1.丰度气泡图-----

#读入相对丰度数据
df<-read.csv("气泡.csv",sep = ",",header = T,check.names = F)
#宽数据转化为长数据
library(dplyr)
library(tidyr)
library(ggplot2)
library(RColorBrewer)
library(stringr)
df2 <- pivot_longer(df, cols = -Tax, names_to = "samples", values_to = "value")

col=c("#c74732","#187c65","#023f75","#FB8072", "#FFED6F","#BC80BD", "#8DD3C7" , "#FCCDE5","#B3DE69","#CCEBC5","#BEBADA","#FC8D62")
head(df2)#查看转换后获得的长数据的前几行
#合并分组数据
group<- read.csv('group.csv', header = T,sep = ",")
df3 <- merge(df2,group,by = 'samples')
p11<-ggplot(df3, aes(x = Ecosystems, y = Tax, size =value, colour =Ecosystems))+geom_point()+labs(size="  Relative\nabundance%",x="Ecosystems",y="Genus")+guides(colour="none")+ scale_color_manual(values = col)+ theme_bw()+theme(panel.background = element_blank(),legend.key = element_blank(),panel.grid.major = element_line(color = "gray",linetype = 2,linewidth = 0.25),panel.border = element_rect(color="black",fill=NA),text=element_text(size=14,family="serif",color = "black"),axis.text.y = element_text(size = 12, family = "serif",face = "italic",color = "black", hjust = 1, vjust = .5),axis.text.x = element_text(size = 12, family = "serif",color = "black"))+scale_y_discrete(limits=c("Geobacter","Rhodomicrobium","Desulfovirga","Sideroxydans","Pseudomonas","Geothrix","Pedomicrobium","Thiobacillus","Ferrimicrobium","Anaeromyxobacter","Tumebacillus","Clostridium"))
col<-brewer.pal(12, 'Paired')
p12<-ggplot(df3, aes(x =Site, y = Tax, size =value, colour =Site))+geom_point()+labs(size="  Relative\nabundance%",x="Site",y="Genus")+guides(colour="none")+scale_color_manual(values = col)+ theme_bw()+theme(panel.background = element_blank(),legend.key = element_blank(),panel.grid.major = element_line(color = "gray",linetype = 2,linewidth = 0.2),panel.border = element_rect(color="black",fill=NA),text=element_text(size=14,family="serif",color = "black"),axis.text.y = element_text(size = 12, family = "serif",face = "italic",color = "black", hjust = 1, vjust = .5),axis.text.x = element_text(size = 12, family = "serif",color = "black"))+scale_x_discrete(limits=c("LD","DF","GZ","QY","WX","JN","SY","HL"))+scale_y_discrete(limits=c("Geobacter","Rhodomicrobium","Desulfovirga","Sideroxydans","Pseudomonas","Geothrix","Pedomicrobium","Thiobacillus","Ferrimicrobium","Anaeromyxobacter","Tumebacillus","Clostridium"))
p13<-ggplot(df3, aes(x =ts, y = Tax, size =value, colour =Tax))+geom_point()+ scale_color_manual(values = col)+scale_size_continuous(range(0,5))+ theme_bw()+theme(panel.background = element_blank(),legend.key = element_blank(),panel.grid.major = element_line(color = "gray",linetype = 2),panel.border = element_rect(color="black",fill=NA),text=element_text(size=16,family="serif"))
p12<-p12+theme(legend.position = 'none')
p11<-p11

#----2.丰度柱状图----

library(ggplot2)
library(cowplot)#拼图的R包
library(ggprism)
df<-read.csv("丰度柱状图.csv",sep = ",",header = T,check.names = F)
group<- read.csv('group.csv', header = T,sep = ",")
row<- read.csv('rowname.csv', header = T,sep = ",")
df1 <- merge(df,group,by = 'samples')
cols=c("#c74732","#187c65","#023f75","#FB8072", "#FFED6F","#BC80BD", "#8DD3C7" , "#FCCDE5","#B3DE69","#CCEBC5","#BEBADA","#FC8D62")
##方差分析
#方差齐性检验bartlett.test
nom <- bartlett.test(df1$Rela~df1$Ecosystems,data =df1)
#单因素方差分析整体检验
oneway<-aov(df1$Rela~df1$Ecosystems,data =df1)
anova(oneway)
#LSD多重比较 
library(agricolae)
out <- duncan.test(oneway,"df1$Ecosystems")
out
#整理绘图所需数据
mar<-out$groups
rownamemar<-row.names(mar)
newmar<-data.frame(rownamemar,mar$`df1$Rela`,mar$groups)
sort<-newmar[order(newmar$rownamemar),]
# 将groups的数据框按列名排序，目的是保持与均值标准差的数据一一对应
rowname<-row.names(out$means)
mean<-out$means[,1]
se <-((out$means[,2])/sqrt(9))#这儿的数字需要改成自己的重复数
marker<-sort$mar.groups
plotdata<-data.frame(rowname,mean,se,marker)
plotdata
p21<-ggplot(plotdata, aes(x =rowname, y =mean, color=rowname)) +
  geom_bar(stat = "identity", position = position_dodge(), linewidth=0.8,width = 0.7,alpha=0) +geom_text(aes(label=marker,y=mean+se+0.005),size=6,position= position_dodge(0.6),family="serif")+
  geom_errorbar(aes(ymin = mean, ymax = mean + se), 
                position = position_dodge(0.7), width = 0.15) +#调整误差线长度
  scale_color_manual(values = cols) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
  labs(x = "Ecosystems", y = "Fe-redox associated bacteria（community）relative abundance/%") +
  theme_prism(base_fontface = "plain",
              base_family = "serif",
              base_size = 14,
              base_line_size = 0.8)+theme(legend.position = 'none')
cols<-brewer.pal(12, 'Paired')
###site
##方差分析
#方差齐性检验bartlett.test
nom <- bartlett.test(df1$Rela~df1$Site,data =df1)
#单因素方差分析整体检验
oneway<-aov(df1$Rela~df1$Site,data =df1)
anova(oneway)
#LSD多重比较
library(agricolae)
out <- duncan.test(oneway,"df1$Site")
out
#整理绘图所需数据http://127.0.0.1:21125/graphics/plot_zoom_png?width=565&height=403
mar<-out$groups
rownamemar<-row.names(mar)
newmar<-data.frame(rownamemar,mar$`df1$Rela`,mar$groups)
sort<-newmar[order(newmar$rownamemar),]
# 将groups的数据框按列名排序，目的是保持与均值标准差的数据一一对应
rowname<-row.names(out$means)
mean<-out$means[,1]
se <-((out$means[,2])/sqrt(9))#这儿的数字需要改成自己的重复数
marker<-sort$mar.groups
plotdata<-data.frame(rowname,mean,se,marker)
plotdata
p22<-ggplot(plotdata, aes(x =rowname, y =mean, color =rowname)) +
  geom_bar(stat = "identity", position = position_dodge(), width = 0.7,linewidth=0.8,alpha=0) +geom_text(aes(label=marker,y=mean+se+0.005),size=6,position= position_dodge(0.6),family="serif")+
  geom_errorbar(aes(ymin =mean, ymax = mean + se), 
                position = position_dodge(0.7), width = 0.15) +#调整误差线长度
  scale_color_manual(values = cols) +scale_x_discrete(limits=c("LD","DF","GZ","QY","WX","JN","SY","HL"))+
  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
  labs(x = "Site", y = "Fe-redox associated bacteria（community） relative abundance/%") +
  theme_prism(base_fontface = "plain",
              base_family = "serif",
              base_size = 14,
              base_line_size = 0.8)+theme(legend.position = 'none')
cols=c("#c74732","#187c65","#023f75","#FB8072", "#FFED6F","#BC80BD", "#8DD3C7" , "#FCCDE5","#B3DE69","#CCEBC5","#BEBADA","#FC8D62")
###site&type
##方差分析
#方差齐性检验bartlett.test
nom <- bartlett.test(df1$Rela~df1$st,data =df1)
#单因素方差分析整体检验
oneway<-aov(df1$Rela~df1$st,data =df1)
anova(oneway)
#LSD多重比较
library(agricolae)
out <- duncan.test(oneway,"df1$st")
out
#整理绘图所需数据
mar<-out$groups
rownamemar<-row.names(mar)
newmar<-data.frame(rownamemar,mar$`df1$Rela`,mar$groups)
sort<-newmar[order(newmar$rownamemar),]
# 将groups的数据框按列名排序，目的是保持与均值标准差的数据一一对应
rowname<-row.names(out$means)
mean<-out$means[,1]
se <-((out$means[,2])/sqrt(9))#这儿的数字需要改成自己的重复数
marker<-sort$mar.groups
plotdata<-data.frame(rowname,mean,se,marker)
plotdata
plotdata1<- merge(plotdata,row,by = 'rowname')
p23<-ggplot(plotdata1, aes(x =Site, y =mean, color=Ecosystems)) +
  geom_bar(stat = "identity", linewidth=0.8,position = position_dodge(), width = 0.7,alpha=0) + labs(fill="Ecosystems",x = "Site", y = "Fe-redox associated bacteria（community） relative abundance/%")+
  geom_errorbar(aes(ymax = mean + se,ymin=mean), 
                position = position_dodge(0.7), width = 0.15) +#调整误差线长度
  scale_color_manual(values = cols,name="Ecosystems") + 
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)))  +
  theme_prism(base_fontface = "plain",
              base_family = "serif",
              base_size = 14,
              base_line_size = 0.8)
#拼图
library(patchwork)
p1<-p12+p11+p22+p21+ plot_annotation(tag_levels = 'A')+plot_layout(widths = c(5, 3))
p1
ggsave("丰度.pdf",width =12,height =8)
#----3.α多样性----
#加载包
library(ggplot2)
library(ggthemes)
library(tidyverse)
library(agricolae)
library(car)
library(reshape2)
library(vegan)
color=c("#c74732","#187c65","#023f75","#FB8072", "#FFED6F","#BC80BD", "#8DD3C7" , "#FCCDE5","#B3DE69","#CCEBC5","#BEBADA","#FC8D62")
##导入数据，所需是数据行名为样本名、列名为OTUxxx的数据表
df<-read.csv("newotu.csv", header=T, sep=",",row.names = 1, check.names = F)
#使用vegan包计算多样性指数
Shannon <- diversity(df, index = "shannon", MARGIN = 2, base = exp(1))
Simpson <- diversity(df, index = "simpson", MARGIN = 2, base =  exp(1))
Richness <- specnumber(df, MARGIN = 2)#spe.rich =sobs
###将以上多样性指数统计成表格
index <- as.data.frame(cbind(Shannon, Simpson, Richness))
tdf <- t(df)#转置表格
tdf<-ceiling(as.data.frame(t(df)))
#计算obs，chao，ace指数
obs_chao_ace <- t(estimateR(tdf))
obs_chao_ace <- obs_chao_ace[rownames(index),]#统一行名
#将obs，chao，ace指数与前面指数计算结果进行合并
index$Chao <- obs_chao_ace[,2]
index$Ace <- obs_chao_ace[,4]
index$obs <- obs_chao_ace[,1]
#计算Pielou及覆盖度
index$Pielou <- Shannon / log(Richness, 2)
index$Goods_coverage <- 1 - colSums(df ==1) / colSums(df)
#导出表格
write.table(cbind(sample=c(rownames(index)),index),'diversity.index.csv', row.names = F, sep = ',', quote = F)
#读入文件
index <- read.csv('diversity.index.csv', header = T, row.names = 1,sep = ",")
index$samples <- rownames(index)#将样本名写到文件中
groups<- read.csv('group.csv', header = T,sep = ",")
colnames(groups)[1:2] <- c('samples','Ecosystems')
df2 <- merge(index,groups,by = 'samples')

#方差检验
model<-aov(Shannon ~ Ecosystems, data=df2)
#多重比较
out <- duncan.test(model,"Ecosystems")
print(out$groups)
# 标记字母法数据准备
mark <- data.frame(out$groups)
mark$group1 = rownames(mark)
head(mark)
#mark$group1 <- as.character(mark$group1)
str(mark)
#绘图
p31<-ggplot(df2,aes(Ecosystems,Shannon,fill=Ecosystems))+geom_violin(alpha = 0,aes(color=Ecosystems),
      scale = 'width',
      trim = TRUE)+
  stat_boxplot(geom = "errorbar", width=0)+geom_boxplot(position="dodge",linewidth=1,width=0.25,fill="white",aes(color=Ecosystems),outlier.shape =NA)+
  geom_jitter(aes(fill=Ecosystems,color=Ecosystems), shape=21,size=2,alpha=1,width=0.1)+#添加抖动点
  theme_wsj()+
  guides(fill=guide_legend(title=NULL))+labs(x="Ecosystems",y="Shannon index")+
 annotate("text", x = as.numeric(factor(mark$group1)), y = mark$Shannon + 1.5, label = mark$groups,color ="black", size =5)+#添加字母标记
  theme_bw()+scale_fill_manual(values = color)+scale_color_manual(values = color)+theme_test() +
  theme(text=element_text(size=14,family="serif"),axis.text.y = element_text(size = 12, family = "serif",color = "black", hjust = 1, vjust = .5),axis.text.x = element_text(size = 12, family = "serif",color = "black"),panel.grid=element_blank())+theme(legend.position="none")
p31
#方差检验
model<-aov(Richness ~ Ecosystems, data=df2)
#多重比较
out <- duncan.test(model,"Ecosystems")
print(out$groups)
# 标记字母法数据准备
mark <- data.frame(out$groups)
mark$group1 = rownames(mark)
head(mark)
#mark$group1 <- as.character(mark$group1)
str(mark)
#绘图
p32<-ggplot(df2,aes(Ecosystems,Richness,fill=Ecosystems))+geom_violin(alpha = 0,aes(color=Ecosystems),
      scale = 'width',
      trim = TRUE)+
  stat_boxplot(geom = "errorbar", width=0)+geom_boxplot(position="dodge",linewidth=1,width=0.25,fill="white",aes(color=Ecosystems),outlier.shape =NA)+
  geom_jitter(aes(fill=Ecosystems,color=Ecosystems), shape=21,size=2,alpha=1,width=0.1)+#添加抖动点
  theme_wsj()+
  guides(fill=guide_legend(title=NULL))+labs(x="Ecosystems",y="Richness index")+
  annotate("text", x = as.numeric(factor(mark$group1)), y = mark$Richness +30, label = mark$groups,color ="black", size =5)+#添加字母标记
  theme_bw()+scale_fill_manual(values = color)+scale_color_manual(values = color)+theme_test() +
  theme(text=element_text(size=14,family="serif"),axis.text.y = element_text(size = 12, family = "serif",color = "black", hjust = 1, vjust = .5),axis.text.x = element_text(size = 12, family = "serif",color = "black"),panel.grid=element_blank())+theme(legend.position="none")
p32

#----4.NMDS----
library(vegan)
library(ggforce)
library(ggplot2)
library(plyr)
library(microeco)
library(ggprism)
library(ggpubr)#显示点的形状(ggpubr包内的函数）
library(RColorBrewer) #调色板
library(geomtextpath)
color=c("#c74732","#187c65","#023f75","#FB8072", "#FFED6F","#BC80BD", "#8DD3C7" , "#FCCDE5","#B3DE69","#CCEBC5","#BEBADA","#FC8D62")
data("group") # 分类表
data("otu") # OTU丰度表
otu<-read.csv("otuav.csv", header=T, sep=",",row.names = 1, check.names = F)
group<- read.csv('groupav.csv', header = T,sep = ",",row.names = 1,check.names = F)
inputdata = as.data.frame(t(otu[,rownames(group)])) 
otu.distance<-vegdist(t(otu))
## 计算Bray-Curtis距离
distance_bray <- vegdist(t(otu), method="bray",diag=T, upper=T)
class(distance_bray)
#先把dist转换成matirx
distance_bray_matrix <- as.matrix(distance_bray)
dim(distance_bray_matrix)
#再把matrix转换成dataframe。
distance_bray_frame <- as.data.frame(distance_bray_matrix)
dim(distance_bray_frame)
#基于Bray-Curtis距离做NMDS分析
#NMDS分析一般使用的是Bray-Curtis距离算法
NMDS_bray <- metaMDS(distance_bray_frame, k = 2,eig=T)  #默认维度为k = 2
NMDS_bray$points  #查看每个样本在坐标的位置

NMDS_bray$stress 
# NMDS不能给出每个轴的解释度，但需要标明stress
#对于NMDS二维分析，通常认为stress<0.2时有一定的解释意义；
#当stress<0.1时，可认为是一个好的排序；当 stress<0.05时，则具有很好的代表性。

# 获取各样本在前两个维度的坐标
NMDS_bray_points = as.data.frame(NMDS_bray$points)[,c(1:2)]
head(NMDS_bray_points)
#合并样本坐标和对应的分组信息
NMDS_bray_points = data.frame(NMDS_bray_points, group)
head(NMDS_bray_points)
#进行anosim分析
df=t(otu) 
dfGroup=group# 导入分组文件
df.dist=vegdist(df)#利用vegdist进行分析，默认方法bray，也可以手动修改
df.ano1=anosim(df.dist, dfGroup$Ecosystems, permutations =999)
df.ano2=anosim(df.dist, dfGroup$Site, permutations =999)

#绘图
#通常需要标记stress信息，不标记轴的权重信息。 annotate("text",label ="stress = 0.1833631 ",x = -0.6, y = 0.7)labs(title=paste0("Stress: ", round(NMDS_bray$stress ,4)))
p41 <- ggplot(NMDS_bray_points,aes(MDS1,MDS2)) +geom_hline(yintercept=0, linetype=2,linewidth=0.5,color="gray")+
  geom_vline(xintercept=0 ,linetype=2,linewidth=0.5,color="gray")+
  geom_point(size=4,alpha=1,aes(shape=Site,color=Ecosystems,fill=Ecosystems))+
  # geom_text(aes(label=rownames(pcoa_bray_points)), size=4, vjust=-1, hjust=0)+shape=21,size=2.5,alpha=0.6,width=0.3
  annotate("text",size=4,family="serif",label =paste0("Stress=", round(NMDS_bray$stress ,4)),x = -0.4, y = 0.7)+theme_test()+scale_shape_manual(values=c(15,16,17,18,19,20,22,25,24))+theme(text=element_text(size=12,family="serif"))+scale_color_manual(values=color)+scale_fill_manual(values=color)

p41
#添加椭圆,color=c("#FDB462","#A6D854","#80B1D3")
library(ggforce)
p42<-p1+stat_ellipse(aes(color=Ecosystems), alpha=0,geom ='polygon',level = 0.95,linewidth=0.5,size=5, show.legend = F)+scale_color_manual(values=color)
p42
#添加多边形
p43<-p41+stat_chull(aes(color=Ecosystems),geom = "polygon",alpha=0)+stat_conf_ellipse(aes(color=Ecosystems),geom = "polygon",level = 0.95,fill=NA,
                    linetype="longdash",size=1,
                    show.legend = FALSE)+scale_color_manual(values=color)
#进行anosim分析
otu<-read.csv("newotu.csv", header=T, sep=",",row.names = 1, check.names = F)
group<- read.csv('group.csv', header = T,sep = ",",row.names = 1,check.names = F)
df=t(otu) 
dfGroup=group# 导入分组文件
df.dist=vegdist(df)#利用vegdist进行分析，默认方法bray，也可以手动修改
df.ano=anosim(df.dist, dfGroup$Ecosystems, permutations =999)#进行anosim分析

#adonis
set.seed(123)
t1<-adonis2(df~Ecosystems,group,permutations = 999,method="bray")
t2<-adonis2(df~Site,group,permutations = 999) 
t3<-adonis2(df~Ecosystems+Site,group,permutations = 999, method = "bray",by = "margin")
t4<-adonis2(df~Ecosystems*Site,group,permutations = 999, method = "bray",
        by = NULL)
t5<-adonis2(df~Ecosystems*Site,group,permutations = 999,tmethod = "bray",
        by = "terms")

#绘制三线表
library(ggpubr)
p44<-ggtexttable(t5[c("Ecosystems","Site","Ecosystems:Site"),c("Df","R2","F","Pr(>F)")], theme = ttheme("blank")) %>% tab_add_hline(at.row = 1:2, row.side = "top", linewidth =3)  %>% tab_add_hline(at.row = nrow(t5[c("Ecosystems","Site","Ecosystems:Site"),c("Df","R2","F","Pr(>F)")])+1, row.side = "bottom", linewidth = 2) 
#拼图
p2<-(p31/p32)|p43+plot_annotation(tag_levels = 'A')
p2
ggsave("多样性.pdf",width =12,height =8,dpi = 1200)

#----5.RDA------------------------------------------------------
setwd("C:\\Users\\yyds\\Desktop\\new")
library(pacman)
p_load(ggplot2,patchwork,vegan,geosphere,psych,corrplot,
       permute,lattice,ggpubr,RColorBrewer,tidyverse,graphics)

#挑选
df=read.csv("newotu.csv",row.names = 1)#读入物种(以genus水平为例)矩阵表
env<-read.csv("RDAenv.csv", header=T, sep=",",row.names = 1, check.names = F)
group<-read.csv("group.csv", header=T, sep=",", check.names = F)
df<-data.frame(t(df))
print(decorana(df))#根据DCA1的AxisLengths值进行选择，如果>4.0选CCA；如果在3.0-4.0之间，选RDA和CCA都可以；如果<3.0, 选择RDA分析即可。
df<- decostand(df,method = "hellinger")


otu.tab.0 <- rda(df ~ 1, env) #no variables
#删除掉共线性的环境因子，删掉最大的变量，直到所有的变量都小于10
otu.tab.1 <-rda(df ~ MAT+MAP+pH+TC+Fed+TN+Latitude+C_N+AP,env)
vif.cca(otu.tab.1)
#进一步筛选
otu.tab.1 <-rda(df ~ MAT+MAP+pH+TC+Fed+TN+C_N+AP, env)
vif.cca(otu.tab.1)
#进一步筛选
otu.tab.1<-rda(df ~ MAT+MAP+pH+Fed+TN+C_N+AP, env)
vif.cca(otu.tab.1)
#检测最低AIC值
library(Formula)
library(devtools)
mod.d<-step(otu.tab.0,scope = (list(lower=formula(otu.tab.0),upper=formula(otu.tab.1))))

df=read.csv("新属总丰度.csv",row.names = 1)#读入物种(以genus水平为例)矩阵表
env<-read.csv("RDAenv2.csv", header=T, sep=",",row.names = 1, check.names = F)
group<-read.csv("group.csv", header=T, sep=",", check.names = F)
df<-data.frame(t(df))
print(decorana(df))#根据DCA1的AxisLengths值进行选择，如果>4.0选CCA；如果在3.0-4.0之间，选RDA和CCA都可以；如果<3.0, 选择RDA分析即可。
df<- decostand(df,method = "hellinger")
color=c("#c74732","#187c65","#023f75","#FB8072", "#FFED6F","#BC80BD", "#8DD3C7" , "#FCCDE5","#B3DE69","#CCEBC5","#BEBADA","#FC8D62")
#------dbRDA------
#计算样方距离，以 Bray-curtis 距离为例，详情 ?vegdist
B.rda<- capscale(df~., env, distance = 'bray', add = TRUE)
#提取样本得分
B.rda.data=data.frame(B.rda$CCA$u[,1:2])
#将绘图数据和分组合并
B.rda.data <- data.frame(samples = rownames(B.rda.data),B.rda.data,row.names = NULL)
df_rda <- merge(B.rda.data,group,by="samples")

#提取物种得分
B.rda.spe=data.frame(B.rda$CCA$v[,1:2])
B.rda.spe=as.data.frame(B.rda.spe)
B.rda.spe$Species<-rownames(B.rda.spe)

#提取环境因子得分
B.rda.env <- B.rda$CCA$biplot[,1:2]
B.rda.env <- as.data.frame(B.rda.env)
head(B.rda.env,n=3)
#anova.cca检验
B.perm=permutest(B.rda,permu=999) # permu=999是表示置换999次
B.perm #是做环境因子整体与群落结构差异的相关性(解释量)，anova.cca {vegan}
#envfit检验   envfit函数跟mantel(见下文)的功能是一样的
B.ef=envfit(B.rda,env,permu=999)#是做每一个环境因子与群落结构差异的相关性(解释量)
r=B.ef$vectors$r#R2值
p=B.ef$vectors$pvals#P值
#每一个环境因子对群落结构差异解释量的柱形图绘制的数据整理tax=rownames(B.rda.env),
cor_com=data.frame(tax=rownames(B.rda.env),B.r=B.ef$vectors$r,B.p=B.ef$vectors$pvals)
cor_com=arrange(cor_com,B.r)
head(cor_com,n=3)
cor_com[c(3)]=cor_com[c(3)]>0.05
head(cor_com,n=3)
#将p<0.05标记为FALSE，p>0.05标记为TRUE，使用此数据绘制柱形图，将其可视化
#envfit检验可视化
cor_com$tax = factor(cor_com$tax,order = T,levels = row.names(cor_com))#按R2值排序

p51<- ggplot(cor_com,aes(x=tax,y=B.r),size=2) +
       geom_bar(stat = 'identity', width = 0.8,color="black",fill="dodgerblue4") +
       scale_fill_manual(values = color)+
       geom_text(aes(y = B.r+0.01, label = ifelse(B.p==TRUE,"","*")),
            size = 5, fontface = "bold") +
       xlab("Environmental factor")+
       ylab(expression(r^"2"))+
       scale_y_continuous(limits = c(0,1))+
       ggprism::theme_prism()+
       theme(axis.text.x = element_text(angle =45))+theme(text=element_text(size=14,family="serif"))
p51
p501=ggplot(data=df_rda,aes(CAP1,CAP2))+
       geom_point(aes(color=Ecosystems,fill=Ecosystems,shape=Site ),size=4)+
       scale_color_manual(values=color)+
       scale_shape_manual(values = c(15,16,17,18,19,20,22,25,24))+
       scale_fill_manual(values = color)+
       geom_point(data=B.rda.spe,aes(CAP1,CAP2),pch=0,size=5)+
       geom_text(data=B.rda.spe,aes(x=B.rda.spe[,1],y=B.rda.spe[,2],label=Species),
            size=4,family="serif",fontface= "italic",colour="black",hjust=1,vjust=0.5)+
       labs(
         x=paste("CAP1",round(B.rda$CCA$eig[1]/sum(B.rda$CCA$eig)*100,2)," %"),
         y=paste("CAP2",round(B.rda$CCA$eig[2]/sum(B.rda$CCA$eig)*100,2)," %"))+
       geom_hline(yintercept = 0,lty=3)+
       geom_vline(xintercept = 0,lty=3)+labs(shape = "Site",color = "Ecosystems")+theme_test()+
       geom_segment(data=B.rda.env,aes(x=0,y=0,xend=B.rda.env[,1],yend=B.rda.env[,2]),
               colour="#545454",linewidth=0.8,arrow=arrow(angle =15,type = "closed",length=unit(0.3,"cm")))+
       geom_text(data=B.rda.env,aes(x=B.rda.env[,1],y=B.rda.env[,2],
          label=rownames(B.rda.env)),size=5,family="serif",fontface= "bold",colour="black",hjust="inward",vjust=0.7*(1-sign(B.rda.env[,2])))+#hjust=(1-sign(B.rda.env[,1]))/2,angle=(180/pi)*atan(B.rda.env[,2]/B.rda.env[,1])
          theme(text=element_text(size=14,family="serif"))
p501
data <- as.data.frame(df)
species.distance<-vegdist(data,method = 'bray')
soil <- NULL
for (i in 1:ncol(env)) {
   dd <- mantel(species.distance, vegdist(env[,i], method = "euclidean"), 
                method = "spearman", permutations = 999, na.rm = TRUE)
   soil <- rbind(soil,c(colnames(env)[i],dd$statistic, dd$signif))
}

#partial mantel
#我们随机构建第三个矩阵的数据
veg.dist<-vegdist(scale(df), method="euclidean")#进行dist格式矩阵转化

#MAT
env.dist <- vegdist(scale(env[,c(2:7)]), method="euclidean")#进行dist格式矩阵转化
soil.dist <- vegdist(scale(env[,1]), method="euclidean")#进行dist格式矩阵转化
mantel.partial(veg.dist, soil.dist, env.dist, method = "spearman",
               permutations = 999) #控制了环境变量，探究物种与土壤养分的关系
#MAP
env.dist <- vegdist(scale(env[,c(1,3:7)]), method="euclidean")#进行dist格式矩阵转化
soil.dist <- vegdist(scale(env[,2]), method="euclidean")#进行dist格式矩阵转化
mantel.partial(veg.dist, soil.dist, env.dist, method = "spearman",
               permutations = 999) #控制了环境变量，探究物种与土壤养分的关系
#pH
env.dist <- vegdist(scale(env[,c(1:2,4:7)]), method="euclidean")#进行dist格式矩阵转化
soil.dist <- vegdist(scale(env[,3]), method="euclidean")#进行dist格式矩阵转化
mantel.partial(veg.dist, soil.dist, env.dist, method = "spearman",
               permutations = 999) #控制了环境变量，探究物种与土壤养分的关系
#Fed
env.dist <- vegdist(scale(env[,c(1:3,5:7)]), method="euclidean")#进行dist格式矩阵转化
soil.dist <- vegdist(scale(env[,4]), method="euclidean")#进行dist格式矩阵转化
mantel.partial(veg.dist, soil.dist, env.dist, method = "spearman",
               permutations = 999) #控制了环境变量，探究物种与土壤养分的关系
#TN
env.dist <- vegdist(scale(env[,c(1:4,6:7)]), method="euclidean")#进行dist格式矩阵转化
soil.dist <- vegdist(scale(env[,5]), method="euclidean")#进行dist格式矩阵转化
mantel.partial(veg.dist, soil.dist, env.dist, method = "spearman",
               permutations = 999) #控制了环境变量，探究物种与土壤养分的关系
#C_N
env.dist <- vegdist(scale(env[,c(1:5,7)]), method="euclidean")#进行dist格式矩阵转化
soil.dist <- vegdist(scale(env[,6]), method="euclidean")#进行dist格式矩阵转化
mantel.partial(veg.dist, soil.dist, env.dist, method = "spearman",
               permutations = 999) #控制了环境变量，探究物种与土壤养分的关系
#AP
env.dist <- vegdist(scale(env[,c(1:6)]), method="euclidean")#进行dist格式矩阵转化
soil.dist <- vegdist(scale(env[,7]), method="euclidean")#进行dist格式矩阵转化
mantel.partial(veg.dist, soil.dist, env.dist, method = "spearman",
               permutations = 999) #控制了环境变量，探究物种与土壤养分的关系

#-------普通RDA------
B.rda<- rda(df,env,scale = T)#RDA分析，如果没有环境因子参数，就是PCA分析
#提取样本得分
B.rda.data=data.frame(B.rda$CCA$u[,1:2])
#将绘图数据和分组合并
B.rda.data <- data.frame(samples = rownames(B.rda.data),B.rda.data,row.names = NULL)
df_rda <- merge(B.rda.data,group,by="samples")

#提取物种得分
B.rda.spe=data.frame(B.rda$CCA$v[,1:2])
B.rda.spe=as.data.frame(B.rda.spe)
B.rda.spe$Species<-rownames(B.rda.spe)

#提取环境因子得分
B.rda.env <- B.rda$CCA$biplot[,1:2]
B.rda.env <- as.data.frame(B.rda.env)
head(B.rda.env,n=3)
#anova.cca检验
B.perm=permutest(B.rda,permu=999) # permu=999是表示置换999次
B.perm #是做环境因子整体与群落结构差异的相关性(解释量)，anova.cca {vegan}
#envfit检验   envfit函数跟mantel(见下文)的功能是一样的
B.ef=envfit(B.rda,env,permu=999)#是做每一个环境因子与群落结构差异的相关性(解释量)
r=B.ef$vectors$r#R2值
p=B.ef$vectors$pvals#P值
#每一个环境因子对群落结构差异解释量的柱形图绘制的数据整理tax=rownames(B.rda.env),
cor_com=data.frame(tax=rownames(B.rda.env),B.r=B.ef$vectors$r,B.p=B.ef$vectors$pvals)
cor_com=arrange(cor_com,B.r)
head(cor_com,n=3)
cor_com[c(3)]=cor_com[c(3)]>0.05
head(cor_com,n=3)
#将p<0.05标记为FALSE，p>0.05标记为TRUE，使用此数据绘制柱形图，将其可视化
#envfit检验可视化
cor_com$tax = factor(cor_com$tax,order = T,levels = row.names(cor_com))#按R2值排序

p51<- ggplot(cor_com,aes(x=tax,y=B.r),size=2) +
       geom_bar(stat = 'identity', width = 0.8,color="black",fill="dodgerblue4") +
       scale_fill_manual(values = color)+
       geom_text(aes(y = B.r+0.01, label = ifelse(B.p==TRUE,"","*")),
            size = 5, fontface = "bold") +
       xlab("Environmental factor")+
       ylab(expression(r^"2"))+
       scale_y_continuous(limits = c(0,1))+
       ggprism::theme_prism()+
       theme(axis.text.x = element_text(angle =45))+theme(text=element_text(size=14,family="serif"))
p51


#带有环境因子，物种信息且进行不同月份不同处理标记的RDA图
p5=ggplot(data=df_rda,aes(RDA1,RDA2))+
       geom_point(aes(color=Ecosystems,fill=Ecosystems,shape=Site ),size=4)+
       scale_color_manual(values=color)+
       scale_shape_manual(values = c(15,16,17,18,19,20,22,25,24))+
       scale_fill_manual(values = color)+
       geom_point(data=B.rda.spe,aes(RDA1,RDA2),pch=0,size=5)+
       geom_text(data=B.rda.spe,aes(x=B.rda.spe[,1],y=B.rda.spe[,2],label=Species),
            size=4,family="serif",fontface= "italic",colour="black",hjust=1,vjust=0.5)+
       labs(
         x=paste("RDA1",round(B.rda$CCA$eig[1]/sum(B.rda$CCA$eig)*100,2)," %"),
         y=paste("RDA2",round(B.rda$CCA$eig[2]/sum(B.rda$CCA$eig)*100,2)," %"))+
       geom_hline(yintercept = 0,lty=3)+
       geom_vline(xintercept = 0,lty=3)+labs(shape = "Site",color = "Ecosystems")+theme_test()+
       geom_segment(data=B.rda.env,aes(x=0,y=0,xend=B.rda.env[,1],yend=B.rda.env[,2]),
               colour="#545454",linewidth=0.8,arrow=arrow(angle =15,type = "closed",length=unit(0.3,"cm")))+
       geom_text(data=B.rda.env,aes(x=B.rda.env[,1],y=B.rda.env[,2],
          label=rownames(B.rda.env)),size=5,family="serif",fontface= "bold",colour="black",hjust="inward",vjust=0.7*(1-sign(B.rda.env[,2])))+#hjust=(1-sign(B.rda.env[,1]))/2,angle=(180/pi)*atan(B.rda.env[,2]/B.rda.env[,1])
          theme(text=element_text(size=14,family="serif"))
p5
ggsave("RDA.pdf",width =8,height =6)
#mantel检验
data <- as.data.frame(df)
species.distance<-vegdist(data,method = 'bray')
soil <- NULL
for (i in 1:ncol(env[,1:13])) {
   dd <- mantel(species.distance, vegdist(env[,i], method = "euclidean"), 
                method = "spearman", permutations = 999, na.rm = TRUE)
   soil <- rbind(soil,c(colnames(env)[i],dd$statistic, dd$signif))
}
head(soil,n=3)
soil <- data.frame(aa=rownames(B.rda.env),M_r=soil[,2],M.p=soil[,3])
rownames(soil)=soil$aa
soil=arrange(soil,M_r)
soil[c(3)]=soil[c(3)]>0.05 # 将p<0.05标记为FALSE，p>0.05标记为TRUE，同上
soil$aa = factor(soil$aa,order = T,levels = row.names(soil))
soil$M_r=round(as.numeric(soil$M_r),4)
head(soil,n=3)
#mantel检验可视化
p52 <- ggplot(soil, aes(x =aa, y = M_r),size=2) +
       geom_bar(stat = 'identity', width = 0.8,color="black",fill="dodgerblue4") +
       geom_text(aes(y = M_r+0.005, label = ifelse(M.p==TRUE,"","*")),
            size = 5, fontface = "bold") +
       xlab("Environmental factor")+
       ylab(expression(r))+
       ggprism::theme_prism()+
       theme(axis.text.x = element_text(angle =0))+theme(text=element_text(size=12,family="serif"))
p52

#----计算条件效应
df=read.csv("新属总丰度.csv",row.names = 1)#读入物种(以genus水平为例)矩阵表
df<-t(df)
#物种多度数据在进行RDA分析之前要hellinger转化
spe.hel<- decostand(df,method = "hellinger")
# 基于Hellinger 转化的鱼类数据RDA，解释变量为对象env包括的环境变量
# 省略模式的公式
spe.rda <-rda(spe.hel~., env)
#获取各一个因子的conditional effect
anova(spe.rda, by = "term", permutations=999)
RsquareAdj(rda(spe.hel ~ Fed, data=env))$adj.r.squared
RsquareAdj(rda(spe.hel ~ Fed+C_N, data=env))$adj.r.squared
RsquareAdj(rda(spe.hel ~ Fed+C_N+MAT, data=env))$adj.r.squared
RsquareAdj(rda(spe.hel ~ Fed+C_N+MAT+pH, data=env))$adj.r.squared
RsquareAdj(rda(spe.hel ~ Fed+C_N+MAT+pH+AP, data=env))$adj.r.squared
RsquareAdj(rda(spe.hel ~ Fed+C_N+MAT+pH+AP+TN, data=env))$adj.r.squared
RsquareAdj(rda(spe.hel ~ Fed+C_N+MAT+pH+AP+TN+MAP, data=env))$adj.r.squared
#可视化
ex<-read.csv("explain.csv",header = T)

ex[c(4)]<-ex[c(4)]>0.002
p55<- ggplot(ex,aes(x=reorder(Name,-Explains),y=Explains),size=2) +
       geom_bar(stat = 'identity', width = 0.8,color="black",fill="dodgerblue4") +
       scale_fill_manual(values = color)+
       geom_text(aes(y = Explains+1.5, label = ifelse(p==FALSE,"***","**")),
            size = 5, fontface = "bold") +geom_text(aes(y = Explains+1,label =Explains,size = 5, fontface = "bold"))+
       xlab("Environmental factor")+
       ylab("Explains (%)")+
       scale_y_continuous(limits = c(0,15))+
       ggprism::theme_prism()+
       theme(axis.text.x = element_text(angle =45))+theme(text=element_text(size=14,family="serif"))
p55
#----6.相关性和mantel---------
setwd("C:\\Users\\yyds\\Desktop\\new")
#加载包
library(vegan)
library(linkET)
library(dplyr)
library(ggplot2)
library(corrplot)
df<-read.csv("新属总丰度.csv", header=T, sep=",",row.names = 1, check.names = F)
env<-read.csv("mantel2env.csv", header=T, sep=",",row.names = 1, check.names = F)
df<-data.frame(t(df))
mantel <- mantel_test(spec=df, env=env[,1:16],#输入数据
                      spec_select = list(Fe_redox_associated_bacteria_community= 1:12),spec_dist =  dist_func(.FUN = "vegdist", method = "bray"),env_dist = dist_func(.FUN = "vegdist", method = "euclidean"), #样本距离使用的vegdist()计算，可以选择适合自己数据的距离指数。
                     mantel_fun = 'mantel', # mantel.partial：partial mantel test则需要设置env_ctrl
                     na_omit=TRUE
                      )%>%#定义多样性数据#定义结构数据
  mutate(rd = cut(r, breaks = c(-Inf,0.1,0.2,0.3,Inf),
                  labels = c("< 0.1", "0.1 - 0.2","0.2-0.3", ">=0.3")),#定义Mantel的R值范围标签，便于出图
         pd = cut(p, breaks = c(-Inf, 0.001,0.01, 0.05, Inf),
                  labels = c("< 0.001", "0.001 - 0.01","0.01-0.05", ">= 0.05")))#定义Mantel检验的p值范围标签，便于出图

p61<-correlate(env[,1:16], method = "spearman", engine = "Hmisc") %>% 
  as_md_tbl(type ="lower", diag = FALSE) %>%
  qcorrplot() +#热图绘制
  geom_square() +#热图绘制
   geom_mark(size =5, only_mark = T,  # T换成F为显示具体数值  
 sig_level = c(0.01, 0.05), sig_thres = 0.05) + # 设置显著性
  geom_couple(aes(colour = pd, size = rd),data = mantel,curvature = nice_curvature(),alpha=1)+#aes里面是线条格式，data对应的是mantel test 计算结果，curvature控制线条曲率
  scale_fill_gradient2(high ="#c74732", mid = 'white',low ="#187c65",limits = c(-1, 1), #设置范围
                       breaks = seq(-1, 1, by = 0.4)) +scale_size_manual(values = c(1,2,3,4))+
   scale_colour_manual(values = c("#c74732","#ea894e","#FDB462","#999999")) +
  guides(size = guide_legend(title = "Mantel's r",##guides()函数调整标签样式
                             override.aes = list(colour = "grey35"),
                             order = 2),
         colour = guide_legend(title = "Mantel's p", 
                               override.aes = list(size = 3), 
                               order = 1),
         fill = guide_colorbar(title = "Spearman'r", order = 3))+ theme(text=element_text(size=16,family="serif"),axis.text.y = element_text(size =12, family = "serif",color = "black", hjust = 1, vjust = .5),axis.text.x = element_text(size = 12, family = "serif",color = "black",angle=45))
p61
#partial mantel
#我们随机构建第三个矩阵的数据
veg.dist<-vegdist(scale(df), method="euclidean")#进行dist格式矩阵转化
#Latitude
env.dist <- vegdist(scale(env[,c(2:13)]), method="euclidean")#进行dist格式矩阵转化
soil.dist <- vegdist(scale(env[,1]), method="euclidean")#进行dist格式矩阵转化
mantel.partial(veg.dist, soil.dist, env.dist, method = "spearman",
               permutations = 999) #控制了环境变量，探究物种与土壤养分的关系
#MAT
env.dist <- vegdist(scale(env[,c(1,3:13)]), method="euclidean")#进行dist格式矩阵转化
soil.dist <- vegdist(scale(env[,2]), method="euclidean")#进行dist格式矩阵转化
mantel.partial(veg.dist, soil.dist, env.dist, method = "spearman",
               permutations = 999) #控制了环境变量，探究物种与土壤养分的关系
#MAP
env.dist <- vegdist(scale(env[,c(1:2,4:13)]), method="euclidean")#进行dist格式矩阵转化
soil.dist <- vegdist(scale(env[,3]), method="euclidean")#进行dist格式矩阵转化
mantel.partial(veg.dist, soil.dist, env.dist, method = "spearman",
               permutations = 999) #控制了环境变量，探究物种与土壤养分的关系
#pH
env.dist <- vegdist(scale(env[,c(1:3,5:13)]), method="euclidean")#进行dist格式矩阵转化
soil.dist <- vegdist(scale(env[,4]), method="euclidean")#进行dist格式矩阵转化
mantel.partial(veg.dist, soil.dist, env.dist, method = "spearman",
               permutations = 999) #控制了环境变量，探究物种与土壤养分的关系
#TC
env.dist <- vegdist(scale(env[,c(1:4,6:13)]), method="euclidean")#进行dist格式矩阵转化
soil.dist <- vegdist(scale(env[,5]), method="euclidean")#进行dist格式矩阵转化
mantel.partial(veg.dist, soil.dist, env.dist, method = "spearman",
               permutations = 999) #控制了环境变量，探究物种与土壤养分的关系
#TN
env.dist <- vegdist(scale(env[,c(1:5,7:13)]), method="euclidean")#进行dist格式矩阵转化
soil.dist <- vegdist(scale(env[,6]), method="euclidean")#进行dist格式矩阵转化
mantel.partial(veg.dist, soil.dist, env.dist, method = "spearman",
               permutations = 999) #控制了环境变量，探究物种与土壤养分的关系
#C/N
env.dist <- vegdist(scale(env[,c(1:6,8:13)]), method="euclidean")#进行dist格式矩阵转化
soil.dist <- vegdist(scale(env[,7]), method="euclidean")#进行dist格式矩阵转化
mantel.partial(veg.dist, soil.dist, env.dist, method = "spearman",
               permutations = 999) #控制了环境变量，探究物种与土壤养分的关系
#AP
env.dist <- vegdist(scale(env[,c(1:7,9:13)]), method="euclidean")#进行dist格式矩阵转化
soil.dist <- vegdist(scale(env[,8]), method="euclidean")#进行dist格式矩阵转化
mantel.partial(veg.dist, soil.dist, env.dist, method = "spearman",
               permutations = 999) #控制了环境变量，探究物种与土壤养分的关系
#NH4
env.dist <- vegdist(scale(env[,c(1:8,10:13)]), method="euclidean")#进行dist格式矩阵转化
soil.dist <- vegdist(scale(env[,9]), method="euclidean")#进行dist格式矩阵转化
mantel.partial(veg.dist, soil.dist, env.dist, method = "spearman",
               permutations = 999) #控制了环境变量，探究物种与土壤养分的关系
#NO3
env.dist <- vegdist(scale(env[,c(1:9,11:13)]), method="euclidean")#进行dist格式矩阵转化
soil.dist <- vegdist(scale(env[,10]), method="euclidean")#进行dist格式矩阵转化
mantel.partial(veg.dist, soil.dist, env.dist, method = "spearman",
               permutations = 999) #控制了环境变量，探究物种与土壤养分的关系
#Fed
env.dist <- vegdist(scale(env[,c(1:10,12:13)]), method="euclidean")#进行dist格式矩阵转化
soil.dist <- vegdist(scale(env[,11]), method="euclidean")#进行dist格式矩阵转化
mantel.partial(veg.dist, soil.dist, env.dist, method = "spearman",
               permutations = 999) #控制了环境变量，探究物种与土壤养分的关系
#Fep
env.dist <- vegdist(scale(env[,c(1:11,13)]), method="euclidean")#进行dist格式矩阵转化
soil.dist <- vegdist(scale(env[,12]), method="euclidean")#进行dist格式矩阵转化
mantel.partial(veg.dist, soil.dist, env.dist, method = "spearman",
               permutations = 999) #控制了环境变量，探究物种与土壤养分的关系
#Feo
env.dist <- vegdist(scale(env[,c(1:12)]), method="euclidean")#进行dist格式矩阵转化
soil.dist <- vegdist(scale(env[,13]), method="euclidean")#进行dist格式矩阵转化
mantel.partial(veg.dist, soil.dist, env.dist, method = "spearman",
               permutations = 999) #控制了环境变量，探究物种与土壤养分的关系
#菌属与环境因子相关性
corr <- correlate(df, env[,1:17], method = 'spearman')
p62 <- qcorrplot(corr) +
  geom_tile(colour = "grey80", linewidth = 0.25) +
  scale_fill_gradient2(high ="#c74732", mid = 'white',low ="#187c65",limits = c(-1, 1), #设置范围
                       breaks = seq(-1, 1, by = 0.4)) +
  geom_mark(sep = '\n',size =4, sig_level = c(0.05, 0.01, 0.001),
            sig_thres = 0.05, color = 'black',only_mark = T) + theme(text=element_text(size=16,family="serif"),axis.text.x = element_text(angle=45,hjust=1, vjust=1,size = 12, family = "serif",color = "black"),axis.text.y = element_text(size = 12, family = "serif",face="italic",color = "black", hjust = 1, vjust = .5))
ggsave("cor1.png",width =8,height = 6)
#铁碳比率与环境因子相关性
corr <- correlate(env[,22:24],env[,1:21],method = 'spearman')
p63 <- qcorrplot(corr) +
  geom_tile(colour = "grey80", linewidth = 0.25) +
  scale_fill_gradient2(high ="#c74732", mid = 'white',low ="#187c65",limits = c(-1, 1), #设置范围
                       breaks = seq(-1, 1, by = 0.4)) +
  geom_mark(sep = '\n',size =4, sig_level = c(0.05, 0.01, 0.001),
            sig_thres = 0.05, color = 'black') + theme(text=element_text(size=16,family="serif"),axis.text.x = element_text(angle=45,hjust=1, vjust=1,size = 12, family = "serif",color = "black"),axis.text.y = element_text(size = 12, family = "serif",face="italic",color = "black", hjust = 1, vjust = .5))
p63
ggsave("pl.png",width =12,height = 4,dpi=600)
#多样性与环境因子相关性
div<-read.csv("diversity.index.csv",row.names = 1,check.names = T)
corr <- correlate(div,env[,1:17],method = 'spearman')
p64 <- qcorrplot(corr) +
  geom_tile(colour = "grey80", linewidth = 0.25) +
  scale_fill_gradient2(high ="#c74732", mid = 'white',low ="#187c65",limits = c(-1, 1), #设置范围
                       breaks = seq(-1, 1, by = 0.4)) +
  geom_mark(sep = '\n',size =4, sig_level = c(0.05, 0.01, 0.001),
            sig_thres = 0.05, color = 'black',only_mark = T) + theme(text=element_text(size=16,family="serif"),axis.text.x = element_text(angle=45,hjust=1, vjust=1,size = 12, family = "serif",color = "black"),axis.text.y = element_text(size = 12, family = "serif",face="italic",color = "black", hjust = 1, vjust = .5))
p64

#椭圆那种
library(corrplot)#加载corrplot包
res = corr$r # 取相关性矩阵R值
p = corr$p # 取相关性矩阵p值，这里$p的p为小写
pdf(height=9, width=6,family='serif', bg = "white",file = "correlation_heatmap.pdf")#设置导出的图的高度、宽度、字体、背景色、格式
coul = colorRampPalette(c("#187c65","white","#c74732"))(20)
corrplot(res,col= coul,order = "original",method = "ellipse",tl.cex= 0.6,tl.col ="black",tl.srt = 45, cl.align.text = "l", cl.length = 7, cl.ratio = 0.1, cl.cex = 0.6, p.mat = p, insig="label_sig", sig.level = c(0.001,0.01,0.05),pch.cex = 0.5,mar = c(0.5,0.2,0.2,0.2))
dev.off()
p3<-(p61+p64/p62)/p5+p50+plot_annotation(tag_levels = 'A')+plot_layout(heights=c(9,11),widths = c(11, 9))
p3
ggsave("RDA mantel.pdf",width =13,height =13)
#----7.铁碳比率与环境因子相关性--------

#----8.随机森林------
setwd("C:\\Users\\yyds\\Desktop\\new\\随机森林")
#调用R包
library(ggplot2) #绘图
library(RColorBrewer) #调色板
library(tidyverse) #mutate函数
library(randomForest) #传统随机森林
library(rfPermute) #新型随机森林
color<-c("#D9D9D9","steelblue","#023f75")
#FeC
df<-read.csv("FeC.csv", header=T, sep=",", check.names = F)

#构建模型
set.seed(123)
df.rf <- randomForest(FeC~ ., 
                      data= df, 
                      ntree = 1000,
                      importance=TRUE, proximity=TRUE)#一般都选择T
importance(df.rf, decreasing = F)

#检验每个变量的重要性并构建数据框
set.seed(123)
richness.rfP<- rfPermute(FeC ~ ., data = df, 
                         ntree = 1000,
                         nrep = 299, 
                         num.cores =8)#数据过多可以加大这个数字，多线程运行
importance(richness.rfP, decreasing = F)
richness.data <- data.frame(importance(richness.rfP, decreasing = F))
#%IncMSE和IncNodePurity都可以表示变量的重要性，选择哪个取决于你

#添加p值
richness.data <- mutate(richness.data,
  label = ifelse(X.IncMSE.pval < 0.001, '***',
                 ifelse(X.IncMSE.pval < 0.01, '**',
                        ifelse(X.IncMSE.pval < 0.05, '*', ''))))
#添加变量名
richness.data$name <- rownames(richness.data)
#变量名排序
richness.data$name <- factor(richness.data$name,
                         levels = richness.data$name)
richness.data$IncNodePurity<-c("#4DAF4A","#4DAF4A","#FF7F00","#FF7F00","#A65628","#A65628","#FF7F00","#A65628", "#FF7F00",rep("#A65628",4),"#76B7B2","#FF7F00","#4DAF4A","#377EB8","#76B7B2")
p1<- ggplot(richness.data, aes(name, X.IncMSE)) +
  geom_bar(fill =richness.data$IncNodePurity,
           stat = 'identity') +
  geom_text(aes(y = X.IncMSE + 0.5,
                label = label)) +
  theme_test() +
  labs(title="FeC",x = '',
       y = 'Increase in MSE(%)') +
  theme(legend.position = '') +coord_flip()+
 #坐标轴翻转 
  theme(text=element_text(size=16,family="serif"))

p1
df<-read.csv("FeCo.csv", header=T, sep=",", check.names = F)

#构建模型
set.seed(123)
df.rf <- randomForest(FeCo~ ., 
                      data= df, 
                      ntree = 1000,
                      importance=TRUE, proximity=TRUE)#一般都选择T
importance(df.rf, decreasing = F)

#检验每个变量的重要性并构建数据框
set.seed(123)
richness.rfP<- rfPermute(FeCo~ ., data = df, 
                         ntree = 1000,
                         nrep = 299, 
                         num.cores = 6)#数据过多可以加大这个数字，多线程运行
importance(richness.rfP, decreasing = F)
richness.data <- data.frame(importance(richness.rfP, decreasing = F))
#%IncMSE和IncNodePurity都可以表示变量的重要性，选择哪个取决于你

#添加p值
richness.data <- mutate(richness.data,
  label = ifelse(X.IncMSE.pval < 0.001, '***',
                 ifelse(X.IncMSE.pval < 0.01, '**',
                        ifelse(X.IncMSE.pval < 0.05, '*', ''))))
#添加变量名
richness.data$name <- rownames(richness.data)
#变量名排序
richness.data$name <- factor(richness.data$name,
                         levels = richness.data$name)
richness.data$IncNodePurity<-c(rep("#A65628",2),"#4DAF4A","#A65628","#4DAF4A","#A65628","#4DAF4A",rep("#A65628",2),"#FF7F00","#A65628","#FF7F00","#76B7B2","#76B7B2","#4E79A7")
p2<- ggplot(richness.data, aes(name, X.IncMSE)) +
  geom_bar(fill = richness.data$IncNodePurity,
           stat = 'identity') +
  geom_text(aes(y = X.IncMSE + 0.5,
                label = label)) +
  theme_test() +
  labs(title="FeCo",x = '',
       y = 'Increase in MSE(%)') +
  theme(legend.position = '') +
  coord_flip() +
  theme(text=element_text(size=16,family="serif"))

p2

df<-read.csv("Feo.csv", header=T, sep=",", check.names = F)

#构建模型
set.seed(123)
df.rf <- randomForest(Feo~ ., 
                      data= df, 
                      ntree = 1000,
                      importance=TRUE, proximity=TRUE)#一般都选择T
importance(df.rf, decreasing = F)

#检验每个变量的重要性并构建数据框
set.seed(123)
richness.rfP<- rfPermute(Feo ~ ., data = df, 
                         ntree = 1000,
                         nrep = 299, 
                         num.cores =6)#数据过多可以加大这个数字，多线程运行
importance(richness.rfP, decreasing = F)
richness.data <- data.frame(importance(richness.rfP, decreasing = F))
#%IncMSE和IncNodePurity都可以表示变量的重要性，选择哪个取决于你

#添加p值
richness.data <- mutate(richness.data,
  label = ifelse(X.IncMSE.pval < 0.001, '***',
                 ifelse(X.IncMSE.pval < 0.01, '**',
                        ifelse(X.IncMSE.pval < 0.05, '*', ''))))
#添加变量名
richness.data$name <- rownames(richness.data)
#变量名排序
richness.data$name <- factor(richness.data$name,
                         levels = richness.data$name)
richness.data$IncNodePurity<-c("#4DAF4A",rep("#A65628",2),"#4DAF4A","#A65628","#76B7B2",rep("#A65628",3),"#4DAF4A","#FF7F00",rep("#A65628",1),"#76B7B2","#4E79A7")

p3<- ggplot(richness.data, aes(name, X.IncMSE)) +
  geom_bar(fill = richness.data$IncNodePurity,
           stat = 'identity') +
  geom_text(aes(y = X.IncMSE + 0.5,
                label = label)) +
  theme_test() +
  labs(title="Feo",x = '',
       y = 'Increase in MSE(%)') +
  theme(legend.position = '') +
  coord_flip()+
  theme(text=element_text(size=16,family="serif"))

p3
df<-read.csv("Fep.csv", header=T, sep=",", check.names = F)

#构建模型
set.seed(123)
df.rf <- randomForest(Fep~ ., 
                      data= df, 
                      ntree = 1000,
                      importance=TRUE, proximity=TRUE)#一般都选择T
importance(df.rf, decreasing = F)

#检验每个变量的重要性并构建数据框
set.seed(123)
richness.rfP<- rfPermute(Fep~ ., data = df, 
                         ntree = 1000,
                         nrep = 299, 
                         num.cores = 6)#数据过多可以加大这个数字，多线程运行
importance(richness.rfP, decreasing = F)
richness.data <- data.frame(importance(richness.rfP, decreasing = F))
#%IncMSE和IncNodePurity都可以表示变量的重要性，选择哪个取决于你

#添加p值
richness.data <- mutate(richness.data,
  label = ifelse(X.IncMSE.pval < 0.001, '***',
                 ifelse(X.IncMSE.pval < 0.01, '**',
                        ifelse(X.IncMSE.pval < 0.05, '*', ''))))
#添加变量名
richness.data$name <- rownames(richness.data)
#变量名排序
richness.data$name <- factor(richness.data$name,
                         levels = richness.data$name)
richness.data$IncNodePurity<-c("#A65628","#A65628","#A65628","#76B7B2",rep("#A65628",2),"#4E79A7","#FF7F00","#A65628","#76B7B2",rep("#4DAF4A",3),"#A65628")
p4<- ggplot(richness.data, aes(name, X.IncMSE)) +
  geom_bar(fill = richness.data$IncNodePurity,
           stat = 'identity') +
  geom_text(aes(y = X.IncMSE + 0.5,
                label = label)) +
 theme_test() +
  labs(title="Fep",x = '',
       y = 'Increase in MSE(%)') +
  theme(legend.position = '') +
  coord_flip()+
  theme(text=element_text(size=16,family="serif"))

p4

library("gridExtra")
library("cowplot")
plot_grid(p1,p2,p3,p4,labels="AUTO", ncol=2, nrow=2)#拼图及标注
  ggsave("随机森林排序.pdf",width =14,height =10)
```
